import {
  Star,
  Bell,
  Bike,
  Camera,
  Laptop,
  Settings,
  Wrench,
  House,
  TvMinimalPlay,
  TimerReset,
  Smartphone,
  Briefcase,
  Gamepad2,
  Headphones,
  LetterText,
} from 'lucide-react';
export const categories = [
  { id: 1, name: 'Accessories', icon: <Star />, color: 'red.500' },
  { id: 2, name: 'Art', icon: <LetterText />, color: 'green.500' },
  { id: 3, name: 'Audio', icon: <Bell />, color: 'yellow.500' },
  { id: 4, name: 'Bikes', icon: <Bike />, color: 'pink.500' },
  { id: 5, name: 'Camera', icon: <Camera />, color: 'gray.500' },
  { id: 6, name: 'Laptop', icon: <Laptop />, color: 'blue.500' },
  { id: 7, name: 'Drill Machine', icon: <Settings />, color: 'red.500' },
  { id: 8, name: 'Hand Tools', icon: <Wrench />, color: 'pink.500' },
  { id: 9, name: 'Home Appliances', icon: <House />, color: 'yellow.500' },
  { id: 10, name: 'Movies', icon: <TvMinimalPlay />, color: 'pink.500' },
  { id: 11, name: 'Smart Watches', icon: <TimerReset />, color: 'gray.500' },
  { id: 12, name: 'Smartphone', icon: <Smartphone />, color: 'black' },
  { id: 13, name: 'Tools', icon: <Wrench />, color: 'green.500' },
  { id: 14, name: 'Tool Bag', icon: <Briefcase />, color: 'yellow.700' },
  { id: 15, name: 'Video Games', icon: <Gamepad2 />, color: 'purple.500' },
  { id: 16, name: 'Headphone', icon: <Headphones />, color: 'yellow.700' },
];
